version: '3.9'

services:
  mysql:
    container_name: mysql
    build:
      context: ./infra/docker/infra/mysql
      dockerfile: Dockerfile.test
    volumes:
      - ./infra/mysql/test.ci.cnf:/etc/mysql/conf.d/my.cnf
      - ./infra/mysql/schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - 3306:3306

  firebase:
    container_name: firebase
    build:
      context: ./infra/docker/infra/firebase
      dockerfile: Dockerfile
    working_dir: /var/firebase
    volumes:
      - ./infra/firebase:/var/firebase:cached
    ports:
      - 4000:4000
      - 8080:8080
      - 9099:9099
