version: '3.9'

services:
  teacher_gateway:
    container_name: teacher_gateway
    build:
      context: .
      dockerfile: ./infra/docker/api/gateway/teacher/Dockerfile.development
    working_dir: /go/src/github.com/calmato/shs-web/api
    volumes:
      - ./api:/go/src/github.com/calmato/shs-web/api:cached
      - ./tmp/data/go/pkg/mod:/go/pkg/mod:delegated
      - ./tmp/logs/gateway/teacher:/var/log/api:delegated
    environment:
      - PORT=8080
      - METRICS_PORT=9090
      - LOG_PATH=/var/log/api
      - GCP_SERVICE_KEY_JSON=${GCP_SERVICE_KEY_JSON}
      - GCP_STORAGE_BUCKET_NAME=${GCP_STORAGE_BUCKET_NAME}
      - USER_SERVICE_URL=user_api:8080
    ports:
      - 18000:8080
      - 18001:9090
    command: make dev SERVICE=gateway/teacher

  user_api:
    container_name: user_api
    build:
      context: .
      dockerfile: ./infra/docker/api/user/server/Dockerfile.development
    working_dir: /go/src/github.com/calmato/shs-web/api
    volumes:
      - ./api:/go/src/github.com/calmato/shs-web/api:cached
      - ./tmp/data/go/pkg/mod:/go/pkg/mod:delegated
      - ./tmp/logs/gateway/teacher:/var/log/api:delegated
    environment:
      - PORT=8080
      - METRICS_PORT=9090
      - LOG_PATH=/var/log/api
      - GCP_SERVICE_KEY_JSON=${GCP_SERVICE_KEY_JSON}
      - GCP_STORAGE_BUCKET_NAME=${GCP_STORAGE_BUCKET_NAME}
    ports:
      - 19000:8080
      - 19001:9090
    command: make dev SERVICE=user/server

  swagger_generator:
    container_name: swagger_generator
    build:
      context: ./infra/docker/infra/swagger/generator
      dockerfile: Dockerfile
    working_dir: /var/swagger/src
    volumes:
      - ./docs/swagger:/var/swagger/src:cached
      - ./tmp/data/swagger:/tmp/data/swagger:cached
    command: yarn watch

  swagger_teacher:
    container_name: swagger_ui_teacher
    build:
      context: ./infra/docker/infra/swagger/teacher
      dockerfile: Dockerfile
    volumes:
      - ./tmp/data/swagger/teacher/openapi:/var/swagger:cached
    ports:
      - 9000:8080
    environment:
      SWAGGER_JSON: /var/swagger/openapi.yaml
    depends_on:
      - swagger_generator
