// Code generated by MockGen. DO NOT EDIT.
// Source: validator.go

// Package mock_validation is a generated GoMock package.
package mock_validation

import (
	reflect "reflect"

	messenger "github.com/calmato/shs-web/api/proto/messenger"
	gomock "github.com/golang/mock/gomock"
)

// MockRequestValidation is a mock of RequestValidation interface.
type MockRequestValidation struct {
	ctrl     *gomock.Controller
	recorder *MockRequestValidationMockRecorder
}

// MockRequestValidationMockRecorder is the mock recorder for MockRequestValidation.
type MockRequestValidationMockRecorder struct {
	mock *MockRequestValidation
}

// NewMockRequestValidation creates a new mock instance.
func NewMockRequestValidation(ctrl *gomock.Controller) *MockRequestValidation {
	mock := &MockRequestValidation{ctrl: ctrl}
	mock.recorder = &MockRequestValidationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestValidation) EXPECT() *MockRequestValidationMockRecorder {
	return m.recorder
}

// NotifyLessonDecided mocks base method.
func (m *MockRequestValidation) NotifyLessonDecided(req *messenger.NotifyLessonDecidedRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyLessonDecided", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyLessonDecided indicates an expected call of NotifyLessonDecided.
func (mr *MockRequestValidationMockRecorder) NotifyLessonDecided(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyLessonDecided", reflect.TypeOf((*MockRequestValidation)(nil).NotifyLessonDecided), req)
}
