{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
  - name: grpc
    protocol: TCP
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  {{- if .Values.metrics.enabled }}
  - name: metrics
    protocol: TCP
    port: {{ .Values.metrics.port }}
    targetPort: {{ .Values.metrics.port }}
  {{- end }}
{{- end -}}
