openapi: 3.0.3
info:
  title: SHS Web
  description: 管理者・講師用API
  version: 0.1.0
servers:
- url: http://localhost:18000
  description: 開発環境
tags:
- name: Auth
  description: 認証関連
- name: Teacher
  description: 講師関連
- name: Subject
  description: 授業科目関連
paths:
  # Auth
  /v1/me:
    $ref: './paths/v1/auth.index.yaml'
  # Teachers
  /v1/teachers:
    $ref: './paths/v1/teachers.index.yaml'
  /v1/teachers/{id}:
    $ref: './paths/v1/teachers.id.yaml'
  # Subjects
  /v1/subjects:
    $ref: './paths/v1/subjects.index.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    # Common
    errorResponse:
      $ref: './components/schemas/common.yaml#/errorResponse'
    # Request
    v1CreateTeacherRequest:
      $ref: './components/schemas/v1/teachers.request.yaml#/createTeacherRequest'
    # Response
    v1AuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authResponse'
    v1TeacherResponse:
      $ref: './components/schemas/v1/teachers.response.yaml#/teacherResponse'
    v1TeachersResponse:
      $ref: './components/schemas/v1/teachers.response.yaml#/teachersResponse'
    v1SubjectsResponse:
      $ref: './components/schemas/v1/subjects.response.yaml#/subjectsResponse'
