openapi: 3.0.3
info:
  title: SHS Web
  description: 管理者・講師用API
  version: 0.1.0
servers:
- url: http://localhost:18000
  description: 開発環境
tags:
- name: Auth
  description: 認証関連
- name: Teacher
  description: 講師関連
- name: Subject
  description: 授業科目関連
- name: Schedule
  description: 授業コマ関連
- name: Shift
  description: シフト作成関連
- name: Submission
  description: シフト提出関連
- name: Other
  description: その他
paths:
  # Auth
  /v1/me:
    $ref: './paths/v1/me/index.yaml'
  /v1/me/mail:
    $ref: './paths/v1/me/mail.yaml'
  /v1/me/password:
    $ref: './paths/v1/me/password.yaml'
  /v1/me/subjects:
    $ref: './paths/v1/me/subjects.yaml'
  # Teachers
  /v1/teachers:
    $ref: './paths/v1/teachers/index.yaml'
  /v1/teachers/{teacherId}:
    $ref: './paths/v1/teachers/_teacherId/index.yaml'
  /v1/teachers/{teacherId}/mail:
    $ref: './paths/v1/teachers/_teacherId/mail.yaml'
  /v1/teachers/{teacherId}/password:
    $ref: './paths/v1/teachers/_teacherId/password.yaml'
  /v1/teachers/{teacherId}/role:
    $ref: './paths/v1/teachers/_teacherId/role.yaml'
  /v1/teachers/{teacherId}/subjects:
    $ref: './paths/v1/teachers/_teacherId/subjects.yaml'
  # Students
  # Subjects
  /v1/subjects:
    $ref: './paths/v1/subjects/index.yaml'
  /v1/subjects/{subjectId}:
    $ref: './paths/v1/subjects/_subjectId.yaml'
  # Schedules
  /v1/schedules:
    $ref: './paths/v1/schedules/index.yaml'
  # Shifts
  /v1/shifts:
    $ref: './paths/v1/shifts/index.yaml'
  /v1/shifts/{shiftId}:
    $ref: './paths/v1/shifts/_shiftId/index.yaml'
  /v1/shifts/{shiftId}/schedule:
    $ref: './paths/v1/shifts/_shiftId/schedule.yaml'
  # Submissions
  /v1/teachers/{teacherId}/submissions:
    $ref: './paths/v1/teachers/_teacherId/submissions/index.yaml'
  /v1/teachers/{teacherId}/submissions/{summaryId}:
    $ref: './paths/v1/teachers/_teacherId/submissions/_summaryId.yaml'
  # Other
  /v1/rooms:
    $ref: './paths/v1/rooms/index.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    # Common
    errorResponse:
      $ref: './components/schemas/common.yaml#/errorResponse'
    # Request
    v1UpdateMySubjectsRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateMySubjectsRequest'
    v1UpdateMyMailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateMyMailRequest'
    v1UpdateMyPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateMyPasswordRequest'
    v1CreateTeacherRequest:
      $ref: './components/schemas/v1/teachers.request.yaml#/createTeacherRequest'
    v1UpdateTeacherMailRequest:
      $ref: './components/schemas/v1/teachers.request.yaml#/updateTeacherMailRequest'
    v1UpdateTeacherPasswordRequest:
      $ref: './components/schemas/v1/teachers.request.yaml#/updateTeacherPasswordRequest'
    v1UpdateTeacherRoleRequest:
      $ref: './components/schemas/v1/teachers.request.yaml#/updateTeacherRoleRequest'
    v1UpdateTeacherSubjectsRequest:
      $ref: './components/schemas/v1/teachers.request.yaml#/updateTeacherSubjectsRequest'
    v1CreateSubjectRequest:
      $ref: './components/schemas/v1/subjects.request.yaml#/createSubjectRequest'
    v1UpdateSubjectRequest:
      $ref: './components/schemas/v1/subjects.request.yaml#/updateSubjectRequest'
    v1UpdateSchedulesRequest:
      $ref: './components/schemas/v1/schedules.request.yaml#/updateSchedulesRequest'
    v1UpdateShiftSummaryScheduleRequest:
      $ref: './components/schemas/v1/shifts.request.yaml#/updateShiftSummaryScheduleRequest'
    v1CreateShiftsRequest:
      $ref: './components/schemas/v1/shifts.request.yaml#/createShiftsRequest'
    v1UpsertTeacherShiftsRequest:
      $ref: './components/schemas/v1/shifts.request.yaml#/upsertTeacherShiftsRequest'
    v1UpdateRoomsTotalRequest:
      $ref: './components/schemas/v1/rooms.request.yaml#/updateRoomsTotalRequest'
    # Response
    v1AuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authResponse'
    v1TeacherResponse:
      $ref: './components/schemas/v1/teachers.response.yaml#/teacherResponse'
    v1TeachersResponse:
      $ref: './components/schemas/v1/teachers.response.yaml#/teachersResponse'
    v1SubjectResponse:
      $ref: './components/schemas/v1/subjects.response.yaml#/subjectResponse'
    v1SubjectsResponse:
      $ref: './components/schemas/v1/subjects.response.yaml#/subjectsResponse'
    v1SchedulesResponse:
      $ref: './components/schemas/v1/schedules.response.yaml#/schedulesResponse'
    v1ShiftSummariesResponse:
      $ref: './components/schemas/v1/shifts.response.yaml#/shiftSummariesResponse'
    v1ShiftsResponse:
      $ref: './components/schemas/v1/shifts.response.yaml#/shiftsResponse'
    v1TeacherSubmissionsResponse:
      $ref: './components/schemas/v1/shifts.response.yaml#/teacherSubmissionsResponse'
    v1TeacherShiftsResponse:
      $ref: './components/schemas/v1/shifts.response.yaml#/teacherShiftsResponse'
    v1RoomsTotalResponse:
      $ref: './components/schemas/v1/rooms.response.yaml#/roomsTotalResponse'
