Aopenapi: 3.0.3
info:
  title: SHS Web
  description: 生徒・保護者用API
  version: 0.1.0
servers:
- url: http://localhost:18010
  description: 開発環境
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
