# Default values for gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""

replicaCount: 1
revisionHistoryLimit: 5

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  enabled: true
  type: ClusterIP
  clusterIP: None
  externalPort: 8080
  internalPort: 8080

app:
  port: 8080

metrics:
  enabled: true
  port: 9090

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

health:
  liveness:
    enabled: true
    path: /health
    port: 8080
  readiness:
    enabled: true
    path: /health
    port: 8080

env:
- name: ENV_NAME
  value: "value"

gcpCredentials:
  enabled: true
  name: gcp-credentials
  key: gcp-service-key.json
